steps:
- name: python
  entrypoint: bash
  args: ['-c', 'pip install -U dvc dvc[gs]; dvc pull;']
  id: 'dvc_pull'
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/mlops1-project/project-image-for-deploy', '.', '-f', 'dockerfiles/fastapi_app.dockerfile']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/mlops1-project/project-image-for-deploy']
# Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/mlops1-project/project-image-for-deploy:latest']
# Deploy container image to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args:
  - 'run'
  - 'deploy'
  - 'project-image-for-deploy'
  - '--image'
  - 'gcr.io/mlops1-project/project-image-for-deploy:latest'
  - '--region'
  - 'europe-west1'
