# Training configuration
method: bayes
name: "sweep"
metric:
  name: val_loss
  goal: minimize
parameters:
  name: 
    value: "sweep"
  batch_size:
    values: [32,64,128,256]
  lr: 
    min: 0.0001
    max: 0.01
  num_epochs:
    distribution: constant
    value: 20
