name: Docker Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Use Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Checkout Repository
        uses: actions/checkout@v2

      - uses: iterative/setup-dvc@v1
      - name: Get data
        run: dvc pull
        env:
          GDRIVE_CREDENTIALS_DATA: '${{ secrets.GCP_CREDENTIALS }}'

      - name: Build Docker Image
        run: docker build . --file dockerfiles/train_model.dockerfile --tag my-image-name:$(date +%s)

